on:
  push:
    branches:
      - main
      - action-testing
    paths:
      - '**/*.py'
      - '.github/workflows/build.yaml'
      - '*.txt'

env:
  APP_NAME: "Moss Desktop"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #        os: [ windows-latest, ubuntu-latest, macos-latest ]
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-${{ runner.os }}.txt

      - name: Get pygame directory
        shell: bash
        run: |
          PYGAME_DIR=$(python -c 'import os, pygameextra; print(os.path.dirname(pygameextra.pygame.__file__))')
          echo "PYGAME_DIR=${PYGAME_DIR}" >> $GITHUB_ENV

      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: ${{ matrix.os == 'macos-latest' && 'factory' || 'main' }}
          script-name: moss.py
          mode: app
          disable-console: ${{ github.ref == 'refs/heads/main' }}
          deployment: ${{ github.ref == 'refs/heads/main' }}
          report: compilation-report.xml
          windows-icon-from-ico: assets/icons/moss.ico
          macos-app-icon: assets/icons/moss.png
          macos-app-name: ${{ env.APP_NAME }}
          linux-icon: assets/icons/moss.png
          nofollow-import-to: |
            pymupdf.mupdf
          include-data-dir: |
            assets=assets
          include-data-files: |
            LICENSE=LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }} ${{ runner.os }}
          path: |
            build/moss.exe
            build/moss.bin
            build/moss.app
            compilation-report.xml